### ISSUE TITLE
通知欄に表示されるリアクションアイコンの表示について

### ISSUE THREAD

**Issue by tkmrgit** [syuilo/dolphin#11]
![LSDELLCapture500](https://user-images.githubusercontent.com/28042693/67679265-0ee45380-f9cc-11e9-8dd9-4f2fb9e76238.png)

dolphin.藍.moe に追加したsmiling_aiのようなリアクションをした場合に他のRenoteアクション等と同じようなサイズのせいか横長になってしまう。
対象の画像をCSSで object-fit:contain みたいにして修正すると比率が維持されるのでそんな感じにすると良いと思います。

**Comment by syuilo** [comment]
smiling_aiは正方形だけどなんでだろう
