### ISSUE TITLE
broken federation with Mastodon 

### ISSUE THREAD

**Issue by wakest** [syuilo/dolphin#27]
I cant follow or see https://dolphin.devporto.com/@devporto from my mastodon account https://social.wake.st/@liaizon but they show up just fine from pleroma and misskey. Not sure where the bug is. Let me know if you want me to do any tests.

**Comment by noellabo** [comment]
dolphin.devporto.com seems to be unable to access host-meta. Are you restricted by reverse proxy?
https://dolphin.devporto.com/.well-known/host-meta

**Comment by syuilo** [comment]
From my Dolphin instance, "https://dolphin.devporto.com/@devporto" was successfully displayed and followed.

**Comment by devporto** [comment]
Thanks for testing @wakest 

It's nginx reverse proxy. Any tips so we can look into this @noellabo?

**Comment by noellabo** [comment]
I confirmed that host-meta now responds correctly. Previously it returned 404.

You can now follow from Mastodon v3.0.1. @wakest

**Comment by wakest** [comment]
thanks! its all federating properly now!
