### ISSUE TITLE
Posts From Other Users Are Not Visible

### ISSUE THREAD

**Issue by okpierre** [syuilo/dolphin#34]
After several users are created, they can login and see their own posts but they can’t see posts from other users in timeline view. Could this be a bug @syuilo 

Also posted here:
https://community.devporto.com/t/posts-from-other-users-are-not-visible/92

**Comment by syuilo** [comment]
Make sure the users are following each other.

**Comment by okpierre** [comment]
@syuilo how do they know which user to follow if they can't see posts?

**Comment by syuilo** [comment]
Dolphin displays the posts of users you are following on the timeline. (just like Twitter)
If you want to see someone else ’s posts, you ’ll need to go to their profile page and follow them.
You can display the profile page by entering the user name prefixed with @ in the search dialog.

**Comment by okpierre** [comment]
On Twitter there is a public feed and search so each user can decide which interesting topic and user to follow because they can view it.

On Dolphin new users do not see anything so they think nothing is posted. Is timeline not available for all users? It's just blank screen. 

Are you saying the admin need to go in the list to follow each user manually?

**Comment by syuilo** [comment]
Dolphin is intended for personal use, so if you want to see other users' posts, you need to follow them.

> On Dolphin new users do not see anything so they think nothing is posted.

As mentioned above, Dolphin is intended for personal use, so the new user is you.
If you want to make an instance available to an unspecified number of users, consider using Misskey instead of Dolphin.

**Comment by okpierre** [comment]
Got it! Was hoping for lighter but with more users. Thank you for the details.
