### ISSUE TITLE
Text Not Shown In Default Language

### ISSUE THREAD

**Issue by okpierre** [syuilo/dolphin#40]
This text is not shown in default language (English)

![dolphin-text-japanese](https://user-images.githubusercontent.com/1679025/69488422-3e557700-0e37-11ea-9c75-5536631c2a3c.jpg)

**Comment by syuilo** [comment]
The text has not been translated yet.  Please wait until the translation is complete!
🙏

**Comment by okpierre** [comment]
Where does it get the translation from? Maybe I can help

**Comment by syuilo** [comment]
Please visit https://crowdin.com/project/dolphin-ap.
Thank you!

**Comment by okpierre** [comment]
Can it be translated here also?

https://github.com/syuilo/dolphin/blob/3e86584df32c00b9e78ed56fabd14839cd1c8864/locales/en-US.yml#L193
