### ISSUE TITLE
Frontend locks if "Add to list" is chosen while there are no lists

### ISSUE THREAD

**Issue by f-a11y** [syuilo/dolphin#5]
The frontend locks (scrolling is still possible, but clicking has no action) if you attempt to add (from the profile) a user to a list before creating any lists.

To replicate:
- have no lists
- visit a user's profile page
- select from the ellipse "..." the option addToList

**Comment by syuilo** [comment]
Thank you for reporting!
This issue was fixed just before and will be deployed soon.
🙏
